[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."museum-label"]
  timeout = 26

[functions."creative-process"]
  timeout = 26